export const PROFILE_REPOSITORY_PROVIDER = 'PROFILE_REPOSITORY';
export const PROFILE_SERVICE_PROVIDER = 'PROFILE_SERVICE';
export const PROFILE_USECASE_PROVIDERS = {
  CREATE_PROFILE: 'CREATE_PROFILE',
  FETCH_PROFILE: 'FETCH_PROFILE',
  FETCH_USER_PROFILE: 'FETCH_USER_PROFILE',
  UPDATE_PROFILE: 'UPDATE_PROFILE',
  SEARCH_PROFILES: 'SEARCH_PROFILES',
};
