export const USER_REPOSITORY_PROVIDER = 'USER_REPOSITORY';
export const USER_SERVICE_PROVIDER = 'USER_SERVICE';
export const USER_USECASE_PROVIDERS = {
  FETCH_USER: 'FETCH_USER',
  CREATE_USER: 'CREATE_USER',
  UPDATE_USER: 'UPDATE_USER',
  SEARCH_USERS: 'SEARCH_USERS',
  ACTIVATE_USER: 'ACTIVATE_USER',
  DELETE_USER: 'DELETE_USER',
};
